// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKjTUmcUPJKHHisbRw27NHHFWC2NwV_EI',
    appId: '1:904323758993:web:2a13b75627ecca960ef830',
    messagingSenderId: '904323758993',
    projectId: 'talkdiary-with-gpt',
    authDomain: 'talkdiary-with-gpt.firebaseapp.com',
    databaseURL: 'https://talkdiary-with-gpt-default-rtdb.firebaseio.com',
    storageBucket: 'talkdiary-with-gpt.firebasestorage.app',
    measurementId: 'G-B8QH7SQRCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5NtCoN_DwmDxSNlj_Jx8kxizsGPMAArU',
    appId: '1:904323758993:android:89b2a4d2074d3bdd0ef830',
    messagingSenderId: '904323758993',
    projectId: 'talkdiary-with-gpt',
    databaseURL: 'https://talkdiary-with-gpt-default-rtdb.firebaseio.com',
    storageBucket: 'talkdiary-with-gpt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuzNe3C7rZnBl3L8YKbs8ovZEh2QXQJv0',
    appId: '1:904323758993:ios:3bd1ea92c82a6d680ef830',
    messagingSenderId: '904323758993',
    projectId: 'talkdiary-with-gpt',
    databaseURL: 'https://talkdiary-with-gpt-default-rtdb.firebaseio.com',
    storageBucket: 'talkdiary-with-gpt.firebasestorage.app',
    iosBundleId: 'com.example.talkDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuzNe3C7rZnBl3L8YKbs8ovZEh2QXQJv0',
    appId: '1:904323758993:ios:3bd1ea92c82a6d680ef830',
    messagingSenderId: '904323758993',
    projectId: 'talkdiary-with-gpt',
    databaseURL: 'https://talkdiary-with-gpt-default-rtdb.firebaseio.com',
    storageBucket: 'talkdiary-with-gpt.firebasestorage.app',
    iosBundleId: 'com.example.talkDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKjTUmcUPJKHHisbRw27NHHFWC2NwV_EI',
    appId: '1:904323758993:web:7e2d7673fd235ab50ef830',
    messagingSenderId: '904323758993',
    projectId: 'talkdiary-with-gpt',
    authDomain: 'talkdiary-with-gpt.firebaseapp.com',
    databaseURL: 'https://talkdiary-with-gpt-default-rtdb.firebaseio.com',
    storageBucket: 'talkdiary-with-gpt.firebasestorage.app',
    measurementId: 'G-HWZTSWKGSE',
  );

}